# These are supported funding model platforms

github: [iMsanko]
patreon: iMsanko
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding: 
custom: ['bit.ly/iMsanko', 'link2']
