# These are supported funding model platforms

github: [iMsanko]
patreon: user?u=12720438
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding: 
custom: ['http://bit.ly/iMsanko']
